/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gerald.model.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Position {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Position\",\"namespace\":\"com.gerald.model.avro\",\"types\":[{\"type\":\"enum\",\"name\":\"Suit\",\"symbols\":[\"SPADES\",\"DIAMONDS\",\"CLUBS\",\"HEARTS\"]},{\"type\":\"record\",\"name\":\"MyRecord\",\"fields\":[{\"name\":\"myStrings\",\"type\":{\"type\":\"array\",\"items\":\"string\",\"java-class\":\"java.utils.ArrayList\"}},{\"name\":\"optionalString\",\"type\":[\"string\",\"null\"],\"default\":\"defaultValueTest\"},{\"name\":\"suit\",\"type\":[\"Suit\",\"null\"],\"default\":\"SPADES\"}]},{\"type\":\"record\",\"name\":\"WholeSchema\",\"fields\":[{\"name\":\"myRecord\",\"type\":\"MyRecord\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends Position {
    public static final org.apache.avro.Protocol PROTOCOL = com.gerald.model.avro.Position.PROTOCOL;
  }
}